// <auto-generated />
using System;
using EmployeeManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721110958_SeedEmployees")]
    partial class SeedEmployees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagement.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateHired")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateHired = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = 3,
                            Email = "john.casor@company.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Casor",
                            PhoneNumber = "08012345678",
                            Salary = 350000m
                        },
                        new
                        {
                            Id = 2,
                            DateHired = new DateTime(2021, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1993, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = 2,
                            Email = "mary.johnson@company.com",
                            FirstName = "Mary",
                            IsActive = true,
                            LastName = "Johnson",
                            PhoneNumber = "08087654321",
                            Salary = 420000m
                        },
                        new
                        {
                            Id = 3,
                            DateHired = new DateTime(2020, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1988, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = 1,
                            Email = "david.brown@company.com",
                            FirstName = "David",
                            IsActive = true,
                            LastName = "Brown",
                            PhoneNumber = "08111222333",
                            Salary = 510000m
                        },
                        new
                        {
                            Id = 4,
                            DateHired = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1995, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = 5,
                            Email = "sarah.uche@company.com",
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Uche",
                            PhoneNumber = "07099887766",
                            Salary = 290000m
                        },
                        new
                        {
                            Id = 5,
                            DateHired = new DateTime(2019, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1991, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = 6,
                            Email = "obiageli.taylor@company.com",
                            FirstName = "Obiageli",
                            IsActive = true,
                            LastName = "Taylor",
                            PhoneNumber = "08155667788",
                            Salary = 600000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
